### ISSUE TITLE
Change max-width of central body?

### ISSUE THREAD

**Issue by Regenhardt** [jaywcjlove/markdown-to-html-cli#68]
So the central body element `<markdown-style class="markdown-style">` has a set max-width of 960px, directly on the element. Any way to change this so I can make my site appear wider on wider screens (like `max-width: 80%`)? Tried putting ".markdown-style": "max-width: 80%" in the package.json config but that doesn't work (which makes sense as the styles are directly on the element).

**Comment by jaywcjlove** [comment]
@Regenhardt Upgrade `v3.5.4`

```bash
$ npx markdown-to-html-cli --markdown-style-theme dark --markdown-style "max-width: 1260px"
```

```yml
- name: Converts Markdown to HTML
  uses: jaywcjlove/markdown-to-html-cli@main
  with:
    source: README-zh.md
    output: coverage/action.html
    markdown-style: "max-width: 1260px"
    github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
```
