### ISSUE TITLE
Content outside markdown-style doesn't adapt to dark/light mode changes

### ISSUE THREAD

**Issue by Regenhardt** [jaywcjlove/markdown-to-html-cli#69]
When the system changes from light mode to dark mode, the markdown-style element correctly switches style too.

The body itself though does not. Neither does the dark mode switch, nor the github corner (although the github corner still kinda works in dark mode like this).

I see the dark mode switcher already switches CSS variables on the body and those are used in the markdown-style element, so maybe the dark mode switcher could hook into the system event to trigger the same function there, switching everything between modes, then the markdown-style element doesn't need the hook itself (unless there's other CSS in there I haven't seen, I'm not a web dev😅).

**Comment by jaywcjlove** [comment]
@Regenhardt Follow the system to switch between light and dark themes?

**Comment by Regenhardt** [comment]
Yes the operating system or browser. If the browser is set to follow the OS, the website gets the theme change event when the device (I tried Windows and Android) changes theme. The markdown-style element hooks listens to the, the rest does not.

**Comment by Regenhardt** [comment]
I'd try to do that myself but I don't understand how those html strings in the ts files work, they look jumbled already.

**Comment by jaywcjlove** [comment]
@Regenhardt 

```shell
$ markdown-to-html-cli --dark-mode auto
$ markdown-to-html-cli --dark-mode auto --markdown-style-theme dark
$ markdown-to-html-cli --no-dark-mode --markdown-style-theme dark
$ markdown-to-html-cli --markdown-style-theme dark
```


```yml
- name: Converts Markdown to HTML
  uses: jaywcjlove/markdown-to-html-cli@main
  with:
    source: README-zh.md
    output: coverage/action.html
    dark-mode: auto
    markdown-style-theme: dark
    markdown-style: "max-width: 1260px"
    github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
```
