### ISSUE TITLE
Hide light/dark word on mobile

### ISSUE THREAD

**Issue by Regenhardt** [jaywcjlove/markdown-to-html-cli#70]
On mobile the Dark/Light word of the dark mode toggle goes into the actual content. I think it would work to just hide it and rely on the symbol alone to serve as sufficient hint about what it does:
![grafik](https://github.com/jaywcjlove/markdown-to-html-cli/assets/10476293/ce35854c-3bb3-40f2-817b-1ddefd4e9224)

**Comment by Regenhardt** [comment]
Tried the following but it didn't work, not sure why:
```css
@media(max-width: 1080px) {
  dark-mode span.wrapper > span:nth-last-child() {
    display: none;
  }
}
```

**Comment by jaywcjlove** [comment]
@Regenhardt  Updated 5.0.3: You can use the following CSS selectors to hide the text and icon parts of the `dark-mode` component:

```css
dark-mode::part(text) {
    display: none;
}
dark-mode::part(icon) {
    display: none;
}
```
