### ISSUE TITLE
Running github action results in  ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Jodsderechte** [jaywcjlove/markdown-to-html-cli#72]
When providing 

```YML 
- name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: CrossOriginStuff/DungeonAuraTools/README.md
          output: CrossOriginStuff/DungeonAuraTools.html
````

it results in 

```
Run jaywcjlove/markdown-to-html-cli@main
source: /home/runner/work/Jodsderechte.github.io/Jodsderechte.github.io/CrossOriginStuff/DungeonAuraTools/README.md
error:: [Error: ENOENT: no such file or directory, open '/home/runner/work/Jodsderechte.github.io/Jodsderechte.github.io/CrossOriginStuff/DungeonAuraTools/README.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/work/Jodsderechte.github.io/Jodsderechte.github.io/CrossOriginStuff/DungeonAuraTools/README.md'
}
Error: ENOENT: no such file or directory, open '/home/runner/work/Jodsderechte.github.io/Jodsderechte.github.io/CrossOriginStuff/DungeonAuraTools/README.md'
```

even when using the "copy path" function of said README. The repository seems to be included twice in the path which is weird and might be the source of the problem. If you need any more help or if i'm just stupid let me know
